### ISSUE TITLE
Implement the Binary Trie

### ISSUE THREAD

**Issue by zah** [status-im/nim-eth-trie#1]
You'll be implementing one of the core data structures in Ethereum responsible for storing the stateful data of the smart contracts. Please read the descriptions here:

https://blog.ethereum.org/2015/11/15/merkling-in-ethereum/
https://github.com/ethereum/wiki/wiki/Patricia-Tree

The format of this tree is supposed to change in the Ethereum sharding implementations (the current format has hexary nodes and the new format will use binary nodes). The motivation for this is explained here:
https://github.com/ethereum/wiki/wiki/Wishlist#trie

Existing Python code implementing the new binary trie can be found here:
https://github.com/ethereum/py-trie/blob/master/trie/binary.py

... with some older early experiments here:
https://github.com/ethereum/research/tree/master/trie_research

The expected result is working code with good test coverage and some basic documentation (it will be edited later by a dedicated technical writer provided by our team).

**Comment by pablanopete** [comment]
Note - this bounty to be assigned in ETH as communicated by @zah

**Comment by zah** [comment]
Yes, this bounty has been delivered and the reward has been sent OOB.
