### ISSUE TITLE
[Research] Sparse Merkle Trie

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-eth-trie#19]
Someone asked during today's eth2.0 implementer call if sparse Merkle Trie if sparse merkle trie were implemented.

Relevant:

- Vitalik's spec: https://ethresear.ch/t/data-availability-proof-friendly-state-tree-transitions/1453/6
- Python: https://github.com/ethereum/py-trie/pull/58
-  Go: https://github.com/musalbas/smt

**Comment by zah** [comment]
@jangko expressed interest to work on this. We need 3 upvotes as usual.

**Comment by mratsim** [comment]
Please see also this video from @AlexeyAkhunov at [ECDC Berlin, time 14:57](https://youtu.be/XFwHHbt8icU?list=PLbrz7IuP1hrgIT5FK2emIMm410oLEFlXO&t=897)

And also the following paper: [Efficient Sparse Merkle Trees](https://eprint.iacr.org/2016/683.pdf)

**Comment by jangko** [comment]
time to delve into research materials.

**Comment by zah** [comment]
This has been implemented here:
https://github.com/status-im/nim-eth-trie/pull/20

**Comment by zah** [comment]
The bounty has been paid out:
https://etherscan.io/tx/0xe9b0650a6a9d2f40c3e434827353328c045afe4498abf9d6f77e5d54a2594b94

**Comment by jangko** [comment]
thank you very much. and I'm sorry this week been very busy so I'm really slow finishing ad2 benchmark. I will resume on it soon.

**Comment by mratsim** [comment]
Just to keep track, a new optimizing scheme for Sparse Merkle Trees by Vitalik: https://ethresear.ch/t/optimizing-sparse-merkle-trees/3751
